export const LoginStyles = {
  container: "min-h-screen flex items-center justify-center bg-[#181818] p-4",
  card: "w-full max-w-md bg-[#252525] rounded-2xl p-8 shadow-xl",
  title: "text-white text-3xl font-bold text-center mb-2",
  subtitle: "text-[#9ca3af] text-center mb-8",
  form: "space-y-6",
  inputGroup: "space-y-2",
  label: "text-[#9ca3af] text-sm font-medium",
  input: "w-full bg-[#1a1a1a] border border-[#333] rounded-xl px-4 py-3 text-white placeholder-[#4b5563] focus:outline-none focus:ring-2 focus:ring-[#4ade80] transition-all",
  button: "w-full bg-[#4ade80] hover:bg-[#22c55e] text-[#181818] font-bold py-3 rounded-xl transition-all transform active:scale-[0.98]",
  btnOutline: "border-2 border-[#4ade80] text-[#4ade80] hover:bg-[#4ade80] hover:text-[#181818] font-bold px-42 py-3 rounded-xl transition-all active:scale-[0.98]",
  error: "text-red-400 text-sm text-center mt-4",
  fieldError: "text-red-400 text-xs mt-1",
  errorServer: "flex items-center justify-between mt-4 px-4 py-3 bg-red-500/10 border border-red-500/30 rounded-xl",
  buttonErrorServer:"text-red-400 hover:text-red-300 ml-3 text-lg leading-none", 
  inputInvalid: "w-full bg-[#1a1a1a] border border-red-500 rounded-xl px-4 py-3 text-white placeholder-[#4b5563] focus:outline-none focus:ring-2 focus:ring-red-500 transition-all",
}
