export const NavBarStyles = {
 wrapper: "flex items-center justify-between px-6 py-3 bg-[#1e1e1e] border-b border-[#2e2e2e]",
 brand: "flex items-center gap-3",
 logoCircle: "w-10 h-10 rounded-full bg-[#1a3d2b] flex items-center justify-center text-[#4ade80] font-bold text-base select-none",
 titleGroup: "flex flex-col",
 title: "text-white font-bold text-sm leading-tight",
 subtitle: "text-[#6b7280] text-xs",
 nav: "flex items-center gap-2",
 navLink: "flex items-center gap-2 px-4 py-2 rounded-lg border border-[#3a3a3a] text-[#d1d5db] text-sm hover:bg-[#2a2a2a] transition-colors",
 navLinkActive: "flex items-center gap-2 px-4 py-2 rounded-lg border-2 border-[#4ade80] text-[#4ade80] text-sm font-semibold",
 navButton: "flex items-center gap-2 px-4 py-2 rounded-lg border border-[#3a3a3a] text-[#d1d5db] text-sm hover:bg-[#2a2a2a] transition-colors cursor-pointer bg-transparent",
 navButtonActive: "flex items-center gap-2 px-4 py-2 rounded-lg border-2 border-white text-white text-sm font-semibold cursor-pointer bg-transparent",
 icon: "text-base",
 label: "text-sm",
}